# Generated by Django 4.0.1 on 2022-01-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mudanca',
            old_name='mudana_text',
            new_name='mudanca_text',
        ),
    ]
